name: Linter

on:
  push:
    branches:
      - master 

jobs:
  Linter_test:
    runs-on: macos-latest         

    steps:
      - name: Run a multi-line script
        run: |
          ls -la
          composer list
