name: Linter

on:
  push:
    branches:
      - main

jobs:
  Upload_repo: 
    runs-on: macos-latest
    
    steps:
      - name: upload_repo
        uses: actions/checkout@v2
    
      - name: make_lint
        run: composer run-script phpcs -- --standard=PSR12 src bin
 
  Linter_test: 
    runs-on: macos-latest
    needs: [ Upload_repo ]
     
    steps:
      - name: make_lint
        run: la -la 
