name: Linter

on:
  push:
    branches:
      - main

jobs:
  Upload_repo: 
    runs-on: macos-latest
    
    steps:
      - name: upload_repo
        uses: actions/checkout@v2
      
      - name: composer_install
        run: composer install
    
      - name: make_lint
        run: cat composer.json
 
  Linter_test: 
    runs-on: macos-latest
    needs: [ Upload_repo ]
     
    steps:
      - name: ls
        run: ls -la 
