name: Linter

on:
  push:
    branches:
      - main

jobs:
  Linter_test: 
    runs-on: macos-latest
    
    

    steps:
      - name: upload_repo
        uses: actions/checkout@v2
 
      - name: Run a multi-line script
        run: |
          echo "Hello word!"
          ls -la
          composer list
